### ISSUE TITLE
TimeDateZone arithmetic doesn't match ZonedDateTime

### ISSUE THREAD

**Issue by omus** [JeffreySarnoff/TimesDates.jl#7]
```julia
julia> a = TimeDateZone(TimeDate(DateTime(2018, 3, 25)), tz"Europe/London") + Dates.Day(1)
2018-03-26T00:00:00+01:00

julia> b = TimeDateZone(TimeDate(DateTime(2018, 3, 25)), tz"Europe/London") + Dates.Hour(24)
2018-03-26T00:00:00+01:00

julia> c = ZonedDateTime(2018,3,25,tz"Europe/London") + Dates.Day(1)
2018-03-26T00:00:00+01:00

julia> d = ZonedDateTime(2018,3,25,tz"Europe/London") + Dates.Hour(24)
2018-03-26T01:00:00+01:00

julia> ZonedDateTime(a) == c
true

julia> ZonedDateTime(b) == d
false
```

**Comment by JeffreySarnoff** [comment]
yes, I am aware of this, and hope to fix it by doing less leaning even more on Dates an TimeZones and proving out how to handle the Microseconds+Nanoseconds that may be waiting to be added or subtracted when the result from your software is obtained.

What is a simple and quick to check thing that lets me know if the source time+zone is to be mapped through + or through -, I started keeping the FixedTimeZone (zone).
I would like to avoid comparing returning magnitudes because the comparands may be in different timezones (and chasing that tail would be non-performant)?

**Comment by JeffreySarnoff** [comment]
(thank you for the timely feedback, my _appreciation_)

**Comment by JeffreySarnoff** [comment]
simplified and solidified -- no longer an issue   
I have moved the working space to https://github.com/JeffreySarnoff/NanoTimes.jl    
As I complete this approach, the work there will move here.

**Comment by JeffreySarnoff** [comment]
@omus Would you take a new look at this master.  Tests pass, still your awareness of where to seek logical leaks is of great value.  And not everything is tested yet.

**Comment by omus** [comment]
@JeffreySarnoff I'll try to look over master this week.

**Comment by JeffreySarnoff** [comment]
I am porting some of your tests -- will post next release v0.0.5 when they all pass

**Comment by omus** [comment]
I haven't had the spare time to take a look at this again. This is still on my radar.
